import type { Metadata } from "next";
<<<<<<< HEAD
import "./globals.css";
import { Providers } from "./providers";
import { CartProvider } from "../contexts/CartContext";
import ShellWrapper from "./components/ShellWrapper";

export const metadata: Metadata = {
  title: "CAVIOLDDIE",
  description: "Generated by create next app",
  other: {
    "color-scheme": "light",
  },
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 9978e65bf66107052d9924854091e84bcc0418a7
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" style={{ colorScheme: "light" }}>
      <body>
        <CartProvider>
          <Providers>
            <ShellWrapper>{children}</ShellWrapper>
          </Providers>
        </CartProvider>
      </body>
=======
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 9978e65bf66107052d9924854091e84bcc0418a7
    </html>
  );
}
