// // import type { Metadata } from "next";
// // import "./globals.css";
// // import { Providers } from "./providers";
// // import { CartProvider } from "../contexts/CartContext";
// // import ShellWrapper from "./components/ShellWrapper";

// // export const metadata: Metadata = {
// //   title: "CAVIOLDDIE",
// //   description: "Generated by create next app",
// //   other: {
// //     "color-scheme": "light",
// //   },
// // };

// // export default function RootLayout({
// //   children,
// // }: {
// //   children: React.ReactNode;
// // }) {
// //   return (
// //     <html lang="vi" style={{ colorScheme: "light" }}>
// //       <body>
// //         <CartProvider>
// //           <Providers>
// //             <ShellWrapper>{children}</ShellWrapper>
// //           </Providers>
// //         </CartProvider>
// //       </body>
// //     </html>
// //   );
// // }

// import type { Metadata } from "next";
// import "./globals.css";
// import { Providers } from "./providers";
// import { CartProvider } from "../contexts/CartContext";
// import ShellWrapper from "./components/ShellWrapper";

// export const metadata: Metadata = {
//   title: "CAVIOLDDIE",
//   description: "Generated by create next app",
//   other: {
//     "color-scheme": "light",
//   },
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="vi" style={{ colorScheme: "light" }}>
//       <body>
//         <CartProvider>
//           <Providers>
//             <ShellWrapper>{children}</ShellWrapper>
//           </Providers>
//         </CartProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { CartProvider } from "../contexts/CartContext";
import ShellWrapper from "./components/ShellWrapper";

export const metadata: Metadata = {
  title: "CAVIOLDDIE",
  description: "Generated by create next app",
  other: {
    "color-scheme": "light",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" style={{ colorScheme: "light" }}>
      <body>
        {/* Providers (Redux <Provider store={store}>) phải bọc BÊN NGOÀI
            CartProvider, vì CartContext.tsx dùng useDispatch() bên trong —
            hook này cần có Redux Provider ở phía trên nó trong cây component,
            nếu không sẽ lỗi "could not find react-redux context value". */}
        <Providers>
          <CartProvider>
            <ShellWrapper>{children}</ShellWrapper>
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
