import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { CartProvider } from "../contexts/CartContext";
import ShellWrapper from "./components/ShellWrapper";

export const metadata: Metadata = {
  title: "CAVIOLDDIE",
  description: "Generated by create next app",
  other: {
    "color-scheme": "light",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" style={{ colorScheme: "light" }}>
      <body>
        <CartProvider>
          <Providers>
            <ShellWrapper>{children}</ShellWrapper>
          </Providers>
        </CartProvider>
      </body>
    </html>
  );
}
